version: "1.0"
services:
  db:
    image: postgres:15.4
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-prod
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.2
    container_name: booking_redis

  booking:
    image: booking_app
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-prod
    command: ["/booking/docker/app.sh"]
    ports:
      - 7777:8000
    depends_on:
      - db
      - redis

  celery:
    image: booking_celery
    build:
      context: .
    container_name: booking_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .env-prod
    depends_on:
      - redis

  flower:
    image: booking_flower
    build:
      context: .
    container_name: booking_flower
    command: [ "/booking/docker/celery.sh", "flower" ]
    env_file:
      - .env-prod
    depends_on:
      - redis

volumes:
  postgresdata:
